    // FOR while do while
    // for of
    // for in





// for (let i =1; i<10;i=i*2) {

//   console.log(i);
    
// }    


// while(i<10){
//     console.log(i)
 
//     if(i%2==0){
//         i=i+2
//     }else{
//         i=i+3;
//     }

// }



// let i=11;

// do {
//     console.log(i)
//     i++;
    
// } while (i<10);


// let myarr=[1,2,3,4,5,6];

// // console.log(myarr)

// for (let index = 0; index < myarr.length; index++) {

//     if(index%2==2){
//         console.log(0)
//     }else{
        
//         const element = myarr[index];
//         console.log(element)
//     }

// }



// for (const element of myarr) {
    
//     console.log(element)
// }




// let myobj = {
//     name : "abc",
//     marks: 12,
//     sub:"maths"
// }
// let myarr=[1,2,3,4,5,6];

// for (const key in myarr) {

//     console.log(myarr[key])
    
// }