// console.log("abc" - 2);
// console.log("abc" + 2);


// console.log(true + false);
// console.log("10" == 10);
// console.log("10" === 10);


// console.log(2+2+2+'2'+1+3+'4');
// console.log(2-2-2-'2'-1-3-'4');.



// console.log(1 || "Hello");

// console.log(1 && "Hello");


// let a = 5;
// console.log(a += a *= a);

// a += a *= a

// a+=a


// a=a+a;
// a=10;
// a *= a

// a=a*a;
// a=10*10;
// a=10*5


// a=5*5=25;
// a=a+a=> 25+5=30

// console.log(null == undefined);
// console.log(null === undefined);

// console.log(typeof null)
// console.log(typeof undefined)

// console.log(typeof NaN);
// console.log(typeof null);
// console.log(typeof function(){});
// console.log(typeof class {});

console.log(1 < 2 < 3);
console.log(3 > 2 > 1);